### ISSUE TITLE
关于您的安全背包模组

### ISSUE THREAD

**Issue by YokohuSaki** [AmarokIce/SafetyBackpacks#1]
您的模组我下载下来后发现无法使用，没有任何快捷键以及物品，请您尽快与我联系，这个问题很有可让一个极好的模组就此陨落

**Comment by AmarokIce** [comment]
需要自行配置 Config 后才会提供一个物品
通常可以通过 give 获取

**Comment by YokohuSaki** [comment]
很抱歉我没能在config里面发现任何有关文件，是不是您忘记上传，如果方便的话可以请您指导一下我吗。不胜感激



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月31日(周六) 凌晨0:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AmarokIce/SafetyBackpacks] 关于您的安全背包模组 (Issue #1)




 
需要自行配置 Config 后才会提供一个物品
 通常可以通过 give 获取

**Comment by AmarokIce** [comment]
1.7.10 & 1.20.1 ？

**Comment by YokohuSaki** [comment]
版本号为1.20.1



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月31日(周六) 凌晨0:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AmarokIce/SafetyBackpacks] 关于您的安全背包模组 (Issue #1)




 
1.7.10 &amp; 1.20.1 ？

**Comment by AmarokIce** [comment]
了解，稍后会进行测试

**Comment by YokohuSaki** [comment]
如果有进展请第一时间告知我，这真的很重要。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月31日(周六) 凌晨1:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AmarokIce/SafetyBackpacks] 关于您的安全背包模组 (Issue #1)




 
了解，稍后会进行测试

**Comment by AmarokIce** [comment]
已释出 Release

**Comment by YokohuSaki** [comment]
很抱歉我还是打不开这个






Failure丨Yokohu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmarokIce/SafetyBackpacks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月31日(星期六) 中午1:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AmarokIce/SafetyBackpacks] 关于您的安全背包模组 (Issue #1)





 
已释出 Release

**Comment by AmarokIce** [comment]
无法打开是指？
Config 文件夹中有正确生成 Config 吗
